language: cpp

env:
 - DOCBOOK_XSL=/usr/share/xml/docbook/stylesheet/docbook-xsl/fo/docbook.xsl

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo add-apt-repository --yes ppa:chris-lea/protobuf
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt5core5 qt5-qmake qt5-default
 - sudo apt-get install -qq libprotobuf-dev libprotoc-dev protobuf-compiler
 - sudo apt-get install -qq docbook-xsl fop libservlet2.4-java

script:
 - qmake && make && cd examples && make clean && make && test -s doc/example.html -a -s doc/example.md -a -s doc/example.docbook -a -s doc/example.pdf
